MAKE_WITH_DTLS ?= 0

ifeq ($(MAKE_WITH_DTLS),1)

 ifeq (${wildcard $(CONTIKI)/lib/ext/tinydtls/Makefile},)
  ${error Could not find the tinyDTLS submodule. Please run "git submodule update --init" and try again}
 endif

 CFLAGS += -DWITH_DTLS=1

 MODULES += os/net/app-layer/coap/tinydtls-support
 MODULES += lib/tinydtls ${addprefix lib/tinydtls/,aes sha2 ecc}

endif
